ls:
  .dir: kebab-case
  .*: kebab-case

  .github:
    .dir: regex:.*
  .husky:
    .dir: regex:.*
  apps/client/src/routes/**:
    .*: regex:~?(__)?[a-z0-9\-]+

ignore:
  - .git
  - "**/dist"
  - "**/node_modules"
  - apps/client/src/main.tsx
  - "apps/server/drizzle/**"
  - "apps/server/public/**"
  - "docker/**"
