ls:
  .dir: kebab-case
  .*: kebab-case

  .github:
    .dir: regex:.*
  .husky:
    .dir: regex:.*
  apps/client/src/routes/**:
    .*: regex:~?(__)?[a-z0-9\-]+

ignore:
  # Node dependencies is idiotic to lint
  - "**/node_modules"
  # Dockerfiles have their own naming convention
  - "**/Dockerfile*"
  # Generated code should not be linted
  - .git
  - "**/.playwright"
  - "**/dist"
  - "apps/server/drizzle/**"
