ls:
  .dir: kebab-case
  .*: kebab-case

  .vscode:
    .dir: regex:.*
  .github:
    .dir: regex:.*
  apps/website/src/routes/**:
    .*: regex:~?(__)?[a-z0-9\-]+

ignore:
  - node_modules
  - .git
  - "./*/Dockerfile*"
  - "integrations/db/drizzle/**"
  - "apps/e2e/.playwright"
  - "apps/website/.tanstack"
  - "./{apps,integrations,libraries}/*/.turbo"
  - "./{apps,integrations,libraries}/*/dist"
  - "./{apps,integrations,libraries}/*/node_modules"
