ls:
  .dir: kebab-case
  .*: kebab-case

  .vscode:
    .dir: regex:.*
  .github:
    .dir: regex:.*
  apps/client/src/routes/**:
    .*: regex:~?(__)?[a-z0-9\-]+

ignore:
  - node_modules
  - .git
  - "./*/Dockerfile*"
  - "apps/server/drizzle/**"
  - "apps/e2e/.playwright"
  - "apps/client/.tanstack"
  - "./{apps,packages}/*/.turbo"
  - "./{apps,packages}/*/dist"
  - "./{apps,packages}/*/node_modules"
