ls:
  .dir: kebab-case
  .mjs: camelCase
  .js: camelCase
  .jsx: PascalCase
  .mts: camelCase
  .ts: camelCase
  .tsx: PascalCase
  .d.ts: camelCase
  .github:
    .dir: regex:.*
  .husky:
    .dir: regex:.*

ignore:
  - .git
  - "**/dist"
  - "**/node_modules"
