FROM jc21/nginx-proxy-manager:2.11.3

COPY <<EOF /etc/cont-init.d/mp-entrypoint.sh
#!/bin/bash
rm -rf /data/nginx/custom
cp -r /mp-custom-nginx-config/  /data/nginx/custom
echo "Copying custom nginx config to /data/nginx/custom"
EOF

RUN chmod +x /etc/cont-init.d/mp-entrypoint.sh
COPY ./nginx/ /mp-custom-nginx-config/
