services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        MP_SERVER_URL: wss://k573.dev:9090
    image: ghcr.io/kasper573/mp-app:latest
    restart: always
    ports:
      - "8080"
      - "9090:9090"
    environment:
      PORT: 8080
      HOSTNAME: "k573.dev"
      CORS_ORIGIN: "k573.dev"
  proxy:
    image: "jc21/nginx-proxy-manager:2.11.3"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: "true"
    volumes:
      - proxy-data:/data
      - letsencrypt-data:/etc/letsencrypt
volumes:
  proxy-data:
  letsencrypt-data:
