# This is the production services and environments definition
services:
  pg:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: mp
      POSTGRES_PASSWORD: mp
      POSTGRES_DB: mp
    ports:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build:
      context: .
    image: ghcr.io/kasper573/mp-app:latest
    restart: always
    ports:
      - "8080"
    environment:
      MP_PORT: 8080
      MP_HOSTNAME: "k573.dev"
      MP_CORS_ORIGIN: "k573.dev"
      MP_DATABASE_URL: "postgres://mp:mp@pg:5432/mp"
  proxy:
    image: "jc21/nginx-proxy-manager:2.11.3"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: "true"
    volumes:
      - proxy-data:/data
      - letsencrypt-data:/etc/letsencrypt
volumes:
  proxy-data:
  letsencrypt-data:
