packages:
  - "apps/*"
  - "packages/*"
catalog:
  "@types/node": ^22.13.10
  preact: 10.26.9
  typescript: 5.9.0-beta
  vitest: 3.1.4
  "@babel/plugin-proposal-decorators": 7.27.1
  "@vanilla-extract/vite-plugin": 5.0.6
  vite: 6.3.5
  "@preact/preset-vite": 2.10.2
  tsx: 4.19.2
  dotenv: 17.2.0
  express: 5.1.0
  "@types/express": 5.0.3
