packages:
  - "apps/*"
  - "packages/*"
catalog:
  "@types/node": ^22.13.10
  "@types/react": 19.1.8
  "@types/react-dom": 19.1.6
  preact: 10.11.0
  react: 19.1.0
  react-dom: 19.1.0
  typescript: 5.8.2
  vitest: 3.1.4
  "@vanilla-extract/vite-plugin": 5.0.6
  vite: 6.3.5
  "@vitejs/plugin-react": 4.6.0
  tsx: 4.19.2
