packages:
  - "apps/*"
  - "packages/*"
catalog:
  solid-js: 1.9.5
  pixi.js: 8.3.3
  typescript: 5.8.2
  vitest: 3.1.4
  "@types/node": ^22.13.10
  "@vanilla-extract/vite-plugin": 5.0.6
  "@vanilla-extract/esbuild-plugin": 2.3.18
  "@vanilla-extract/css": 1.17.4
  "@vanilla-extract/recipes": 0.5.7
  "@vanilla-extract/sprinkles": 1.6.5
  tsup: 8.5.0
  vite: 6.3.5
  vite-plugin-solid: 2.11.6
  tsx: 4.19.2
