import type { Tile } from "@mp/std";
import type { AuthToken, UserId, UserIdentity } from "@mp/auth";

// This file should only expose runtime code that is shared between client/server.

// This should end up being primarily constants and utility functions.
export const tokenHeaderName = "token";

/**
 * Diameter in tiles around the player that determines what a player can see and the zoom level of the camera.
 * We have one number for rendering and one for networking to allow for some margin
 * in the renderer so that objects don't pop in and out of view.
 */
export const clientViewDistance = {
  renderedTileCount: 24 as Tile,
  networkFogOfWarTileCount: 32 as Tile,
};

const wellKnownGuestToken = "guest" as AuthToken;

export const guestIdentity: UserIdentity = {
  id: "207eef62-4244-4565-a3cf-645a5bd8f34b" as UserId, // generated by uuid, practically guaranteed to be unique
  name: "Guest",
  token: wellKnownGuestToken,
  roles: new Set(),
};

export { default as transformer } from "superjson";
