// GENERATED by @gel/generate v0.6.4

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $NpcType = {
  static: $.$expr_Literal<$NpcType>;
  patrol: $.$expr_Literal<$NpcType>;
  pacifist: $.$expr_Literal<$NpcType>;
  defensive: $.$expr_Literal<$NpcType>;
  aggressive: $.$expr_Literal<$NpcType>;
  protective: $.$expr_Literal<$NpcType>;
} & $.EnumType<
  "default::NpcType",
  ["static", "patrol", "pacifist", "defensive", "aggressive", "protective"]
>;
const NpcType: $NpcType = $.makeType<$NpcType>(
  _.spec,
  "e452429b-ad44-11f0-a9dd-0bce856c784e",
  _.syntax.literal,
);

export type $ActorModelλShape = $.typeutil.flatten<
  _std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
    modelId: $.PropertyDesc<
      _std.$str,
      $.Cardinality.One,
      true,
      false,
      false,
      false
    >;
    "<modelId[is Character]": $.LinkDesc<
      $Character,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<modelId[is Npc]": $.LinkDesc<
      $Npc,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<modelId": $.LinkDesc<
      $.ObjectType,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
  }
>;
type $ActorModel = $.ObjectType<
  "default::ActorModel",
  $ActorModelλShape,
  null,
  [
    ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588["__exclusives__"],
    {
      modelId: {
        __element__: _std.$str;
        __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne;
      };
    },
  ],
  "default::ActorModel"
>;
const $ActorModel = $.makeType<$ActorModel>(
  _.spec,
  "e4528972-ad44-11f0-945a-a542f15f4e34",
  _.syntax.literal,
);

const ActorModel: $.$expr_PathNode<
  $.TypeSet<$ActorModel, $.Cardinality.Many>,
  null
> = _.syntax.$PathNode($.$toSet($ActorModel, $.Cardinality.Many), null);

export type $AreaλShape = $.typeutil.flatten<
  _std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
    areaId: $.PropertyDesc<
      _std.$str,
      $.Cardinality.One,
      true,
      false,
      false,
      false
    >;
    "<areaId[is Character]": $.LinkDesc<
      $Character,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<areaId[is NpcSpawn]": $.LinkDesc<
      $NpcSpawn,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<areaId": $.LinkDesc<
      $.ObjectType,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
  }
>;
type $Area = $.ObjectType<
  "default::Area",
  $AreaλShape,
  null,
  [
    ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588["__exclusives__"],
    {
      areaId: {
        __element__: _std.$str;
        __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne;
      };
    },
  ],
  "default::Area"
>;
const $Area = $.makeType<$Area>(
  _.spec,
  "e4598a32-ad44-11f0-8d54-3b6fa876215b",
  _.syntax.literal,
);

const Area: $.$expr_PathNode<
  $.TypeSet<$Area, $.Cardinality.Many>,
  null
> = _.syntax.$PathNode($.$toSet($Area, $.Cardinality.Many), null);

export type $CharacterλShape = $.typeutil.flatten<
  _std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
    name: $.PropertyDesc<
      _std.$str,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    maxHealth: $.PropertyDesc<
      _std.$float64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    attackDamage: $.PropertyDesc<
      _std.$float64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    attackRange: $.PropertyDesc<
      _std.$float64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    attackSpeed: $.PropertyDesc<
      _std.$float64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    characterId: $.PropertyDesc<
      _std.$str,
      $.Cardinality.One,
      true,
      false,
      false,
      false
    >;
    coords: $.PropertyDesc<
      _std.$json,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    health: $.PropertyDesc<
      _std.$float64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    online: $.PropertyDesc<
      _std.$bool,
      $.Cardinality.One,
      false,
      false,
      false,
      true
    >;
    speed: $.PropertyDesc<
      _std.$float64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    userId: $.PropertyDesc<
      _std.$uuid,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    xp: $.PropertyDesc<
      _std.$float64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    modelId: $.LinkDesc<
      $ActorModel,
      $.Cardinality.One,
      {},
      false,
      false,
      false,
      false
    >;
    areaId: $.LinkDesc<
      $Area,
      $.Cardinality.One,
      {},
      false,
      false,
      false,
      false
    >;
    inventoryId: $.LinkDesc<
      $Inventory,
      $.Cardinality.One,
      {},
      false,
      false,
      false,
      false
    >;
  }
>;
type $Character = $.ObjectType<
  "default::Character",
  $CharacterλShape,
  null,
  [
    ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588["__exclusives__"],
    {
      characterId: {
        __element__: _std.$str;
        __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne;
      };
    },
  ],
  "default::Character"
>;
const $Character = $.makeType<$Character>(
  _.spec,
  "e460123f-ad44-11f0-a2a7-ab8fb24c5b7e",
  _.syntax.literal,
);

const Character: $.$expr_PathNode<
  $.TypeSet<$Character, $.Cardinality.Many>,
  null
> = _.syntax.$PathNode($.$toSet($Character, $.Cardinality.Many), null);

export type $ItemDefinitionλShape = $.typeutil.flatten<
  _std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
    name: $.PropertyDesc<
      _std.$str,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
  }
>;
type $ItemDefinition = $.ObjectType<
  "default::ItemDefinition",
  $ItemDefinitionλShape,
  null,
  [..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588["__exclusives__"]],
  "default::ConsumableDefinition" | "default::EquipmentDefinition"
>;
const $ItemDefinition = $.makeType<$ItemDefinition>(
  _.spec,
  "e46fcfcf-ad44-11f0-8a79-edf5e84d0be5",
  _.syntax.literal,
);

const ItemDefinition: $.$expr_PathNode<
  $.TypeSet<$ItemDefinition, $.Cardinality.Many>,
  null
> = _.syntax.$PathNode($.$toSet($ItemDefinition, $.Cardinality.Many), null);

export type $ConsumableDefinitionλShape = $.typeutil.flatten<
  $ItemDefinitionλShape & {
    definitionId: $.PropertyDesc<
      _std.$str,
      $.Cardinality.One,
      true,
      false,
      false,
      false
    >;
    maxStackSize: $.PropertyDesc<
      _std.$int64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    "<consumableItemId[is NpcReward]": $.LinkDesc<
      $NpcReward,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<definitionId[is ConsumableInstance]": $.LinkDesc<
      $ConsumableInstance,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<consumableItemId": $.LinkDesc<
      $.ObjectType,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<definitionId": $.LinkDesc<
      $.ObjectType,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
  }
>;
type $ConsumableDefinition = $.ObjectType<
  "default::ConsumableDefinition",
  $ConsumableDefinitionλShape,
  null,
  [
    ...$ItemDefinition["__exclusives__"],
    {
      definitionId: {
        __element__: _std.$str;
        __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne;
      };
    },
  ],
  "default::ConsumableDefinition"
>;
const $ConsumableDefinition = $.makeType<$ConsumableDefinition>(
  _.spec,
  "e4736448-ad44-11f0-94ce-151f12e32fa7",
  _.syntax.literal,
);

const ConsumableDefinition: $.$expr_PathNode<
  $.TypeSet<$ConsumableDefinition, $.Cardinality.Many>,
  null
> = _.syntax.$PathNode(
  $.$toSet($ConsumableDefinition, $.Cardinality.Many),
  null,
);

export type $ItemInstanceλShape = $.typeutil.flatten<
  _std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
    inventoryId: $.LinkDesc<
      $Inventory,
      $.Cardinality.One,
      {},
      false,
      false,
      false,
      false
    >;
  }
>;
type $ItemInstance = $.ObjectType<
  "default::ItemInstance",
  $ItemInstanceλShape,
  null,
  [..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588["__exclusives__"]],
  "default::ConsumableInstance" | "default::EquipmentInstance"
>;
const $ItemInstance = $.makeType<$ItemInstance>(
  _.spec,
  "e4850dac-ad44-11f0-b11b-31b1d49130d1",
  _.syntax.literal,
);

const ItemInstance: $.$expr_PathNode<
  $.TypeSet<$ItemInstance, $.Cardinality.Many>,
  null
> = _.syntax.$PathNode($.$toSet($ItemInstance, $.Cardinality.Many), null);

export type $ConsumableInstanceλShape = $.typeutil.flatten<
  $ItemInstanceλShape & {
    instanceId: $.PropertyDesc<
      _std.$str,
      $.Cardinality.One,
      true,
      false,
      false,
      false
    >;
    stackSize: $.PropertyDesc<
      _std.$int64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    definitionId: $.LinkDesc<
      $ConsumableDefinition,
      $.Cardinality.One,
      {},
      false,
      false,
      false,
      false
    >;
  }
>;
type $ConsumableInstance = $.ObjectType<
  "default::ConsumableInstance",
  $ConsumableInstanceλShape,
  null,
  [
    ...$ItemInstance["__exclusives__"],
    {
      instanceId: {
        __element__: _std.$str;
        __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne;
      };
    },
  ],
  "default::ConsumableInstance"
>;
const $ConsumableInstance = $.makeType<$ConsumableInstance>(
  _.spec,
  "e486ef9f-ad44-11f0-bc69-0fa1ede44647",
  _.syntax.literal,
);

const ConsumableInstance: $.$expr_PathNode<
  $.TypeSet<$ConsumableInstance, $.Cardinality.Many>,
  null
> = _.syntax.$PathNode($.$toSet($ConsumableInstance, $.Cardinality.Many), null);

export type $EquipmentDefinitionλShape = $.typeutil.flatten<
  $ItemDefinitionλShape & {
    definitionId: $.PropertyDesc<
      _std.$str,
      $.Cardinality.One,
      true,
      false,
      false,
      false
    >;
    maxDurability: $.PropertyDesc<
      _std.$int64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    "<equipmentItemId[is NpcReward]": $.LinkDesc<
      $NpcReward,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<definitionId[is EquipmentInstance]": $.LinkDesc<
      $EquipmentInstance,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<definitionId": $.LinkDesc<
      $.ObjectType,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<equipmentItemId": $.LinkDesc<
      $.ObjectType,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
  }
>;
type $EquipmentDefinition = $.ObjectType<
  "default::EquipmentDefinition",
  $EquipmentDefinitionλShape,
  null,
  [
    ...$ItemDefinition["__exclusives__"],
    {
      definitionId: {
        __element__: _std.$str;
        __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne;
      };
    },
  ],
  "default::EquipmentDefinition"
>;
const $EquipmentDefinition = $.makeType<$EquipmentDefinition>(
  _.spec,
  "e477b3d3-ad44-11f0-9364-c7bb8ad2a5c0",
  _.syntax.literal,
);

const EquipmentDefinition: $.$expr_PathNode<
  $.TypeSet<$EquipmentDefinition, $.Cardinality.Many>,
  null
> = _.syntax.$PathNode(
  $.$toSet($EquipmentDefinition, $.Cardinality.Many),
  null,
);

export type $EquipmentInstanceλShape = $.typeutil.flatten<
  $ItemInstanceλShape & {
    durability: $.PropertyDesc<
      _std.$int64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    instanceId: $.PropertyDesc<
      _std.$str,
      $.Cardinality.One,
      true,
      false,
      false,
      false
    >;
    definitionId: $.LinkDesc<
      $EquipmentDefinition,
      $.Cardinality.One,
      {},
      false,
      false,
      false,
      false
    >;
  }
>;
type $EquipmentInstance = $.ObjectType<
  "default::EquipmentInstance",
  $EquipmentInstanceλShape,
  null,
  [
    ...$ItemInstance["__exclusives__"],
    {
      instanceId: {
        __element__: _std.$str;
        __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne;
      };
    },
  ],
  "default::EquipmentInstance"
>;
const $EquipmentInstance = $.makeType<$EquipmentInstance>(
  _.spec,
  "e48a189e-ad44-11f0-a1b7-415c1f1a791a",
  _.syntax.literal,
);

const EquipmentInstance: $.$expr_PathNode<
  $.TypeSet<$EquipmentInstance, $.Cardinality.Many>,
  null
> = _.syntax.$PathNode($.$toSet($EquipmentInstance, $.Cardinality.Many), null);

export type $InventoryλShape = $.typeutil.flatten<
  _std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
    inventoryId: $.PropertyDesc<
      _std.$str,
      $.Cardinality.One,
      true,
      false,
      false,
      false
    >;
    "<inventoryId[is Character]": $.LinkDesc<
      $Character,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<inventoryId[is ItemInstance]": $.LinkDesc<
      $ItemInstance,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<inventoryId[is ConsumableInstance]": $.LinkDesc<
      $ConsumableInstance,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<inventoryId[is EquipmentInstance]": $.LinkDesc<
      $EquipmentInstance,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<inventoryId": $.LinkDesc<
      $.ObjectType,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
  }
>;
type $Inventory = $.ObjectType<
  "default::Inventory",
  $InventoryλShape,
  null,
  [
    ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588["__exclusives__"],
    {
      inventoryId: {
        __element__: _std.$str;
        __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne;
      };
    },
  ],
  "default::Inventory"
>;
const $Inventory = $.makeType<$Inventory>(
  _.spec,
  "e45dd151-ad44-11f0-b797-eb21b3f4c168",
  _.syntax.literal,
);

const Inventory: $.$expr_PathNode<
  $.TypeSet<$Inventory, $.Cardinality.Many>,
  null
> = _.syntax.$PathNode($.$toSet($Inventory, $.Cardinality.Many), null);

export type $NpcλShape = $.typeutil.flatten<
  _std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
    aggroRange: $.PropertyDesc<
      _std.$float64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    attackDamage: $.PropertyDesc<
      _std.$float64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    attackRange: $.PropertyDesc<
      _std.$float64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    attackSpeed: $.PropertyDesc<
      _std.$float64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    maxHealth: $.PropertyDesc<
      _std.$float64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    name: $.PropertyDesc<
      _std.$str,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    npcId: $.PropertyDesc<
      _std.$str,
      $.Cardinality.One,
      true,
      false,
      false,
      false
    >;
    npcType: $.PropertyDesc<
      $NpcType,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    speed: $.PropertyDesc<
      _std.$int64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    modelId: $.LinkDesc<
      $ActorModel,
      $.Cardinality.One,
      {},
      false,
      false,
      false,
      false
    >;
    "<npcId[is NpcSpawn]": $.LinkDesc<
      $NpcSpawn,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<npcId[is NpcReward]": $.LinkDesc<
      $NpcReward,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
    "<npcId": $.LinkDesc<
      $.ObjectType,
      $.Cardinality.Many,
      {},
      false,
      false,
      false,
      false
    >;
  }
>;
type $Npc = $.ObjectType<
  "default::Npc",
  $NpcλShape,
  null,
  [
    ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588["__exclusives__"],
    {
      npcId: {
        __element__: _std.$str;
        __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne;
      };
    },
  ],
  "default::Npc"
>;
const $Npc = $.makeType<$Npc>(
  _.spec,
  "e467027f-ad44-11f0-be26-a11817a4ebce",
  _.syntax.literal,
);

const Npc: $.$expr_PathNode<
  $.TypeSet<$Npc, $.Cardinality.Many>,
  null
> = _.syntax.$PathNode($.$toSet($Npc, $.Cardinality.Many), null);

export type $NpcRewardλShape = $.typeutil.flatten<
  _std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
    itemAmount: $.PropertyDesc<
      _std.$int64,
      $.Cardinality.AtMostOne,
      false,
      false,
      false,
      false
    >;
    rewardId: $.PropertyDesc<
      _std.$str,
      $.Cardinality.One,
      true,
      false,
      false,
      false
    >;
    xp: $.PropertyDesc<
      _std.$float64,
      $.Cardinality.AtMostOne,
      false,
      false,
      false,
      false
    >;
    consumableItemId: $.LinkDesc<
      $ConsumableDefinition,
      $.Cardinality.AtMostOne,
      {},
      false,
      false,
      false,
      false
    >;
    equipmentItemId: $.LinkDesc<
      $EquipmentDefinition,
      $.Cardinality.AtMostOne,
      {},
      false,
      false,
      false,
      false
    >;
    npcId: $.LinkDesc<$Npc, $.Cardinality.One, {}, false, false, false, false>;
  }
>;
type $NpcReward = $.ObjectType<
  "default::NpcReward",
  $NpcRewardλShape,
  null,
  [
    ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588["__exclusives__"],
    {
      rewardId: {
        __element__: _std.$str;
        __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne;
      };
    },
  ],
  "default::NpcReward"
>;
const $NpcReward = $.makeType<$NpcReward>(
  _.spec,
  "e47bcea8-ad44-11f0-9d53-c9e3f36d5dcc",
  _.syntax.literal,
);

const NpcReward: $.$expr_PathNode<
  $.TypeSet<$NpcReward, $.Cardinality.Many>,
  null
> = _.syntax.$PathNode($.$toSet($NpcReward, $.Cardinality.Many), null);

export type $NpcSpawnλShape = $.typeutil.flatten<
  _std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
    coords: $.PropertyDesc<
      _std.$json,
      $.Cardinality.AtMostOne,
      false,
      false,
      false,
      false
    >;
    count: $.PropertyDesc<
      _std.$int64,
      $.Cardinality.One,
      false,
      false,
      false,
      false
    >;
    npcType: $.PropertyDesc<
      $NpcType,
      $.Cardinality.AtMostOne,
      false,
      false,
      false,
      false
    >;
    patrol: $.PropertyDesc<
      _std.$json,
      $.Cardinality.AtMostOne,
      false,
      false,
      false,
      false
    >;
    randomRadius: $.PropertyDesc<
      _std.$int64,
      $.Cardinality.AtMostOne,
      false,
      false,
      false,
      false
    >;
    spawnId: $.PropertyDesc<
      _std.$str,
      $.Cardinality.One,
      true,
      false,
      false,
      false
    >;
    areaId: $.LinkDesc<
      $Area,
      $.Cardinality.One,
      {},
      false,
      false,
      false,
      false
    >;
    npcId: $.LinkDesc<$Npc, $.Cardinality.One, {}, false, false, false, false>;
  }
>;
type $NpcSpawn = $.ObjectType<
  "default::NpcSpawn",
  $NpcSpawnλShape,
  null,
  [
    ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588["__exclusives__"],
    {
      spawnId: {
        __element__: _std.$str;
        __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne;
      };
    },
  ],
  "default::NpcSpawn"
>;
const $NpcSpawn = $.makeType<$NpcSpawn>(
  _.spec,
  "e46c5211-ad44-11f0-826e-a74a09840da3",
  _.syntax.literal,
);

const NpcSpawn: $.$expr_PathNode<
  $.TypeSet<$NpcSpawn, $.Cardinality.Many>,
  null
> = _.syntax.$PathNode($.$toSet($NpcSpawn, $.Cardinality.Many), null);

export {
  NpcType,
  $ActorModel,
  ActorModel,
  $Area,
  Area,
  $Character,
  Character,
  $ItemDefinition,
  ItemDefinition,
  $ConsumableDefinition,
  ConsumableDefinition,
  $ItemInstance,
  ItemInstance,
  $ConsumableInstance,
  ConsumableInstance,
  $EquipmentDefinition,
  EquipmentDefinition,
  $EquipmentInstance,
  EquipmentInstance,
  $Inventory,
  Inventory,
  $Npc,
  Npc,
  $NpcReward,
  NpcReward,
  $NpcSpawn,
  NpcSpawn,
};

type __defaultExports = {
  NpcType: typeof NpcType;
  ActorModel: typeof ActorModel;
  Area: typeof Area;
  Character: typeof Character;
  ItemDefinition: typeof ItemDefinition;
  ConsumableDefinition: typeof ConsumableDefinition;
  ItemInstance: typeof ItemInstance;
  ConsumableInstance: typeof ConsumableInstance;
  EquipmentDefinition: typeof EquipmentDefinition;
  EquipmentInstance: typeof EquipmentInstance;
  Inventory: typeof Inventory;
  Npc: typeof Npc;
  NpcReward: typeof NpcReward;
  NpcSpawn: typeof NpcSpawn;
};
const __defaultExports: __defaultExports = {
  NpcType: NpcType,
  ActorModel: ActorModel,
  Area: Area,
  Character: Character,
  ItemDefinition: ItemDefinition,
  ConsumableDefinition: ConsumableDefinition,
  ItemInstance: ItemInstance,
  ConsumableInstance: ConsumableInstance,
  EquipmentDefinition: EquipmentDefinition,
  EquipmentInstance: EquipmentInstance,
  Inventory: Inventory,
  Npc: Npc,
  NpcReward: NpcReward,
  NpcSpawn: NpcSpawn,
};
export default __defaultExports;
