x-env-files: &env_files
  - .env.shared
  - .env.${DOCKER_COMPOSE_ENV}
  - path: .env.local
    required: false
services:
  mp:
    build:
      dockerfile: ./docker/Dockerfile.mp-${DOCKER_COMPOSE_ENV}
      context: ..
    develop:
      watch:
        - action: sync
          path: ..
          target: /workdir
        - action: rebuild
          path: ../pnpm-lock.yaml
    image: ${DOCKER_REGISTRY_URL}/mp-server:${DOCKER_IMAGE_VERSION}
    restart: always
    env_file: *env_files
    depends_on:
      - postgres
  migrations:
    build:
      dockerfile: ../../docker/Dockerfile.migrations
      context: ../apps/server
    image: ${DOCKER_REGISTRY_URL}/mp-migrations:${DOCKER_IMAGE_VERSION}
    env_file: *env_files
  postgres:
    image: postgres:16.4
    restart: always
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    env_file: *env_files
  prometheus:
    image: prom/prometheus:v2.55.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    env_file: *env_files
  node_exporter:
    image: prom/node-exporter:v1.8.2
    env_file: *env_files
  grafana:
    image: grafana/grafana:10.4.12
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    env_file: *env_files
  caddy:
    build:
      dockerfile: ./Dockerfile.caddy
      context: .
    image: ${DOCKER_REGISTRY_URL}/mp-caddy:${DOCKER_IMAGE_VERSION}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile.${DOCKER_COMPOSE_ENV}:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    env_file: *env_files

volumes:
  grafana-data:
  caddy-data:
  caddy-config:
  prometheus-data:
