FROM caddy:2.8.4-builder AS builder
RUN xcaddy build --with github.com/mholt/caddy-ratelimit
 
FROM caddy:2.8.4
COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["sh", "-c", "caddy run --config /etc/caddy/$CADDY_ENV.Caddyfile"]