x-env-files: &env_files
  - path: .env
    required: false
  - .env.${COMPOSE_ENV}
  - .env.shared

services:
  mp-client:
    env_file: *env_files
    build:
      dockerfile: ./docker/Dockerfile.mp-client
      context: ..
    image: ${DOCKER_REGISTRY_URL:-mp}/mp-client:${DOCKER_IMAGE_VERSION:-latest}
    restart: always
    profiles: ["prod", "test"]
    healthcheck:
      test: curl --fail http://localhost/ || exit 1
      interval: 3s
      timeout: 5s
      retries: 9
    depends_on:
      - mp-server

  mp-server:
    env_file: *env_files
    build:
      dockerfile: ./docker/Dockerfile.mp-server
      context: ..
    image: ${DOCKER_REGISTRY_URL:-mp}/mp-server:${DOCKER_IMAGE_VERSION:-latest}
    restart: always
    profiles: ["prod", "test"]
    depends_on:
      mp-migrations:
        condition: service_started
      keycloak-healthcheck:
        condition: service_healthy

  mp-migrations:
    env_file: *env_files
    build:
      dockerfile: ../../docker/Dockerfile.mp-migrations
      context: ../apps/server
    image: ${DOCKER_REGISTRY_URL:-mp}/mp-migrations:${DOCKER_IMAGE_VERSION:-latest}
    profiles: ["prod", "test"]
    depends_on:
      postgres:
        condition: service_healthy

  keycloak:
    env_file: *env_files
    build:
      dockerfile: ./Dockerfile.keycloak
      context: .
    image: ${DOCKER_REGISTRY_URL:-mp}/mp-keycloak:${DOCKER_IMAGE_VERSION:-latest}
    command: start --optimized --import-realm
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    depends_on:
      postgres:
        condition: service_healthy

  # the keycloak image itself is so bare bones for security reasons that it doesn't have curl,
  # so we use a separate container to run healthchecks on keycloak externally.
  keycloak-healthcheck:
    env_file: *env_files
    image: curlimages/curl
    command: ["sh", "-c", "sleep infinity"]
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://keycloak:9000/health/live"]
      interval: 3s
      timeout: 5s
      retries: 9

  postgres:
    env_file: *env_files
    image: postgres:16.4
    restart: always
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    env_file: *env_files
    image: redis:7.4.1
    restart: always

  prometheus:
    env_file: *env_files
    image: prom/prometheus:v2.55.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  node_exporter:
    env_file: *env_files
    image: prom/node-exporter:v1.8.2

  grafana:
    env_file: *env_files
    image: grafana/grafana:10.4.12
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards

  caddy:
    env_file: *env_files
    build:
      dockerfile: ./Dockerfile.caddy
      context: .
    command: ["caddy", "run", "--config", "/etc/caddy/${COMPOSE_ENV}.Caddyfile"]
    image: ${DOCKER_REGISTRY_URL:-mp}/mp-caddy:${DOCKER_IMAGE_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy:/etc/caddy/
      - caddy-data:/data
      - caddy-config:/config

volumes:
  grafana-data:
  caddy-data:
  caddy-config:
  prometheus-data:
