services:
  keycloak:
    ports:
      - "8080:8080"
  postgres:
    ports:
      - "5432:5432"
  tempo:
    ports:
      - "4317:4317"
  alloy:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  caddy:
    extra_hosts:
      - "host.docker.internal:host-gateway"
