x-env-files: &env_files
  - path: .env
    required: false
  - .env.prod
  - .env.shared

services:
  keycloak:
    env_file: *env_files
  postgres:
    env_file: *env_files
  redis:
    env_file: *env_files
  prometheus:
    env_file: *env_files
  node_exporter:
    env_file: *env_files
  grafana:
    env_file: *env_files
  caddy:
    env_file: *env_files
  mp-client:
    env_file: *env_files
  mp-server:
    env_file: *env_files
  mp-migrations:
    env_file: *env_files
