services:
  mp:
    build:
      dockerfile: ./docker/Dockerfile.mp
      context: ..
    image: ${DOCKER_REGISTRY_URL:-mp}/mp-server:${DOCKER_IMAGE_VERSION:-latest}
    restart: always
    depends_on:
      migrations:
        condition: service_started
      keycloak-healthcheck:
        condition: service_healthy

  migrations:
    build:
      dockerfile: ../../docker/Dockerfile.migrations
      context: ../apps/server
    image: ${DOCKER_REGISTRY_URL:-mp}/mp-migrations:${DOCKER_IMAGE_VERSION:-latest}
    depends_on:
      postgres:
        condition: service_healthy
