include:
  - docker-compose.base.yaml 

x-env-files: &env_files
  - path: .env
    required: false
  - .env.${DOCKER_COMPOSE_ENV}
  - .env.shared

services:
  mp:
    build:
      dockerfile: ./docker/Dockerfile.mp
      context: ..
    image: ${DOCKER_REGISTRY_URL:-mp}/mp-server:${DOCKER_IMAGE_VERSION:-latest}
    restart: always
    depends_on:
      migrations:
        condition: service_started
      keycloak-healthcheck:
        condition: service_healthy
    env_file: *env_files

  migrations:
    build:
      dockerfile: ../../docker/Dockerfile.migrations
      context: ../apps/server
    image: ${DOCKER_REGISTRY_URL:-mp}/mp-migrations:${DOCKER_IMAGE_VERSION:-latest}
    depends_on:
      postgres:
        condition: service_healthy
    env_file: *env_files
