# Docker Compose override for development
# This file is automatically loaded by docker compose and provides development-specific configuration

services:
  # Development version of mp-server with hot reload
  mp-server-dev:
    build:
      dockerfile: ./docker/Dockerfile.mp-server.dev
      context: ..
    volumes:
      # Mount source code for hot reload
      - ../:/workdir:cached
      # Use named volume for node_modules to avoid conflicts with host
      - mp-server-node-modules:/workdir/node_modules
    environment:
      - NODE_ENV=development
      - MP_SERVER_DATABASE_HOST=postgres
      - MP_SERVER_PORT=9999
    ports:
      - "9999:9999"
    depends_on:
      keycloak-healthcheck:
        condition: service_healthy
    env_file:
      - path: .env
        required: false
      - .env.dev
      - .env.shared

  # Development version of mp-client with hot reload
  mp-client-dev:
    build:
      dockerfile: ./docker/Dockerfile.mp-client.dev
      context: ..
    volumes:
      # Mount source code for hot reload
      - ../:/workdir:cached
      # Use named volume for node_modules to avoid conflicts with host
      - mp-client-node-modules:/workdir/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"
    env_file:
      - path: .env
        required: false
      - .env.dev
      - .env.shared

volumes:
  mp-server-node-modules:
  mp-client-node-modules: