services:
  keycloak:
    ports:
      - "8080:8080"
  postgres:
    ports:
      - "5432:5432"
    volumes:
      # Developers may be using postgres for other things,
      # so we use a named volume to avoid conflicts.
      - postgres-data:/var/lib/postgresql/data
  redis:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "6379:6379"
  alloy:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  reverse-proxy:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  pushgateway:
    ports:
      - "9091:9091"

volumes:
  postgres-data:
