FROM denoland/deno:2.1.3
WORKDIR /workdir
USER deno

COPY . .
RUN deno install
ENV NODE_ENV=development
ENV MP_BUNDLE_CLIENT_ENV=true
ENV MP_SERVER_PUBLIC_DIR=/workdir/apps/server/public

CMD [ "deno", "task", "dev" ]