FROM node:20.10.0-alpine3.19
WORKDIR /app

# Install drizzle
RUN apk add jq
COPY ./package.json ./
RUN KIT_VER=$(jq -r '.devDependencies["drizzle-kit"]' package.json) && \
    ORM_VER=$(jq -r '.dependencies["drizzle-orm"]' package.json) && \
    PG_VER=$(jq -r '.dependencies.postgres' package.json) && \
    npm install -g drizzle-kit@$KIT_VER drizzle-orm@$ORM_VER postgres@$PG_VER

# Copy migrations
COPY ./drizzle.config.js .
COPY ./drizzle/ ./drizzle/

CMD ["drizzle-kit", "migrate"]
