# This is the production services and environments definition
services:
  mp:
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    image: ghcr.io/kasper573/mp:latest
    restart: always
    ports:
      - 8080
    depends_on:
      - pg
    environment:
      MP_PORT: 8080
      # MP_HTTP_BASE_URL: "http://localhost:8080"
      # MP_WS_BASE_URL: "ws://localhost:8080"
      # MP_CORS_ORIGIN: "*"
      MP_HTTP_BASE_URL: "https://k573.dev"
      MP_WS_BASE_URL: "wss://k573.dev"
      MP_CORS_ORIGIN: "k573.dev"
      MP_DATABASE_URL: "postgres://mp:mp@pg:5432/mp"
      MP_AUTH_SECRET_KEY: ${MP_AUTH_SECRET_KEY}
      MP_AUTH_PUBLISHABLE_KEY: ${MP_AUTH_PUBLISHABLE_KEY}
      MP_BUILD_VERSION: ${MP_BUILD_VERSION}
  migrations:
    build:
      dockerfile: ./docker/Dockerfile.migrations
      context: ..
    image: ghcr.io/kasper573/mp-migrations:latest
    environment:
      MP_DATABASE_URL: "postgres://mp:mp@pg:5432/mp"
  pg:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: mp
      POSTGRES_PASSWORD: mp
      POSTGRES_DB: mp
    ports:
      - 5432
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus:v2.55.1
    ports:
      - 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  node_exporter:
    image: prom/node-exporter:v1.8.2
    ports:
      - 9100
  grafana:
    image: grafana/grafana:10.4.12
    ports:
      - 3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=grafana.k573.dev
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
  proxy:
    image: jc21/nginx-proxy-manager:2.11.3
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: "true"
    volumes:
      - proxy-data:/data
      - letsencrypt-data:/etc/letsencrypt
      - ./nginx:/data/nginx/custom
volumes:
  proxy-data:
  letsencrypt-data:
  grafana-storage:
  pnpm-store:
