server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system_logs
          __path__: /var/log/*log

  - job_name: mp_client_trace
    static_configs:
      - targets:
          - localhost
        labels:
          job: mp_client_trace_logs
          __path__: ${MP_SERVER_CLIENT_TRACE_LOG_PATH}
    pipeline_stages:
      - json:
          expressions:
            ts: ts
            build_version: buildVersion
            type: type
            session_id: sessionId
            user_id: userId
            message: message
            stack: stack
            args: args
      - timestamp:
          source: ts
          format: ISO8601
      - labels:
          build_version:
          type:
          session_id:
          user_id:

  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: container_logs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          tag:
          stream:
          image_name:
          container_name:
          image_id:
          container_id:
      - output:
          source: output
