// Generated by Grats. Do not edit manually.

import type { GqlScalar } from "grats";
import type { GqlDate as GqlDateInternal } from "./../shared/scalars";
import { GraphQLSchema, GraphQLObjectType, GraphQLNonNull, GraphQLString, GraphQLScalarType } from "graphql";
import { foo as queryFooResolver, whatever as queryWhateverResolver } from "./foo";
export type SchemaConfig = {
    scalars: {
        GqlDate: GqlScalar<GqlDateInternal>;
    };
};
export function getSchema(config: SchemaConfig): GraphQLSchema {
    const FooType: GraphQLObjectType = new GraphQLObjectType({
        name: "Foo",
        fields() {
            return {
                bar: {
                    name: "bar",
                    type: new GraphQLNonNull(GraphQLString)
                }
            };
        }
    });
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                foo: {
                    name: "foo",
                    type: new GraphQLNonNull(FooType),
                    args: {
                        input: {
                            type: GraphQLString
                        }
                    },
                    resolve(_source, args) {
                        return queryFooResolver(args.input);
                    }
                },
                whatever: {
                    name: "whatever",
                    type: new GraphQLNonNull(GraphQLString),
                    resolve() {
                        return queryWhateverResolver();
                    }
                }
            };
        }
    });
    const GqlDateType: GraphQLScalarType = new GraphQLScalarType({
        name: "GqlDate",
        ...config.scalars.GqlDate
    });
    return new GraphQLSchema({
        query: QueryType,
        types: [GqlDateType, FooType, QueryType]
    });
}
