// Generated by Grats. Do not edit manually.

import type { GqlScalar } from "grats";
import type { ActorId as ActorIdInternal, ActorModelId as ActorModelIdInternal } from "./../../../integrations/game-shared/src/actor";
import type { AreaId as AreaIdInternal } from "./../../../integrations/game-shared/src/area";
import type { CharacterId as CharacterIdInternal } from "./../../../integrations/game-shared/src/character";
import type { GqlDate as GqlDateInternal } from "./../shared/date-scalar";
import type { ItemDefinition as ItemDefinitionInternal, ItemReference as ItemReferenceInternal } from "./../../../integrations/game-shared/src/item";
import type { LocalFile as LocalFileInternal, Pixel as PixelInternal, Tile as TileInternal, TimesPerSecond as TimesPerSecondInternal, UrlString as UrlStringInternal } from "./../../../libraries/std/src/types";
import { GraphQLSchema, GraphQLObjectType, GraphQLNonNull, GraphQLList, GraphQLScalarType, GraphQLEnumType, GraphQLString, GraphQLBoolean } from "graphql";
import { actorModelIds as queryActorModelIdsResolver, actorSpritesheetUrl as queryActorSpritesheetUrlResolver } from "./modules/actor";
import { areaFileUrl as queryAreaFileUrlResolver } from "./modules/area";
import { characterList as queryCharacterListResolver, myCharacterId as queryMyCharacterIdResolver } from "./modules/character";
import { defaultSpawnPoint as queryDefaultSpawnPointResolver } from "./modules/spawn-point";
import { isPatchOptimizerEnabled as queryIsPatchOptimizerEnabledResolver, serverVersion as queryServerVersionResolver, testError as queryTestErrorResolver, setPatchOptimizerEnabled as mutationSetPatchOptimizerEnabledResolver } from "./modules/settings";
import { itemDefinition as queryItemDefinitionResolver } from "./modules/item";
export type SchemaConfig = {
    scalars: {
        ActorId: GqlScalar<ActorIdInternal>;
        ActorModelId: GqlScalar<ActorModelIdInternal>;
        AreaId: GqlScalar<AreaIdInternal>;
        CharacterId: GqlScalar<CharacterIdInternal>;
        GqlDate: GqlScalar<GqlDateInternal>;
        ItemDefinition: GqlScalar<ItemDefinitionInternal>;
        ItemReference: GqlScalar<ItemReferenceInternal>;
        LocalFile: GqlScalar<LocalFileInternal>;
        Pixel: GqlScalar<PixelInternal>;
        Tile: GqlScalar<TileInternal>;
        TimesPerSecond: GqlScalar<TimesPerSecondInternal>;
        UrlString: GqlScalar<UrlStringInternal>;
    };
};
export function getSchema(config: SchemaConfig): GraphQLSchema {
    const ActorModelIdType: GraphQLScalarType = new GraphQLScalarType({
        name: "ActorModelId",
        ...config.scalars.ActorModelId
    });
    const UrlStringType: GraphQLScalarType = new GraphQLScalarType({
        name: "UrlString",
        ...config.scalars.UrlString
    });
    const FileUrlTypeType: GraphQLEnumType = new GraphQLEnumType({
        description: "internal: url that only works within the docker network,\npublic: on the internet",
        name: "FileUrlType",
        values: {
            internal: {
                value: "internal"
            },
            public: {
                value: "public"
            }
        }
    });
    const AreaIdType: GraphQLScalarType = new GraphQLScalarType({
        name: "AreaId",
        ...config.scalars.AreaId
    });
    const CharacterIdType: GraphQLScalarType = new GraphQLScalarType({
        name: "CharacterId",
        ...config.scalars.CharacterId
    });
    const CharacterType: GraphQLObjectType = new GraphQLObjectType({
        name: "Character",
        fields() {
            return {
                id: {
                    name: "id",
                    type: new GraphQLNonNull(CharacterIdType)
                },
                name: {
                    name: "name",
                    type: new GraphQLNonNull(GraphQLString)
                }
            };
        }
    });
    const TileType: GraphQLScalarType = new GraphQLScalarType({
        description: "Unit of measurement in 2D tile space.",
        name: "Tile",
        ...config.scalars.Tile
    });
    const TileVectorLikeType: GraphQLObjectType = new GraphQLObjectType({
        name: "TileVectorLike",
        fields() {
            return {
                x: {
                    name: "x",
                    type: new GraphQLNonNull(TileType)
                },
                y: {
                    name: "y",
                    type: new GraphQLNonNull(TileType)
                }
            };
        }
    });
    const SpawnPointType: GraphQLObjectType = new GraphQLObjectType({
        name: "SpawnPoint",
        fields() {
            return {
                areaId: {
                    name: "areaId",
                    type: new GraphQLNonNull(AreaIdType)
                },
                coords: {
                    name: "coords",
                    type: new GraphQLNonNull(TileVectorLikeType)
                }
            };
        }
    });
    const ItemDefinitionType: GraphQLScalarType = new GraphQLScalarType({
        name: "ItemDefinition",
        ...config.scalars.ItemDefinition
    });
    const ItemReferenceType: GraphQLScalarType = new GraphQLScalarType({
        name: "ItemReference",
        ...config.scalars.ItemReference
    });
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                actorModelIds: {
                    name: "actorModelIds",
                    type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(ActorModelIdType))),
                    resolve(_source, _args, context) {
                        return queryActorModelIdsResolver(context);
                    }
                },
                actorSpritesheetUrl: {
                    name: "actorSpritesheetUrl",
                    type: new GraphQLNonNull(UrlStringType),
                    args: {
                        urlType: {
                            type: new GraphQLNonNull(FileUrlTypeType)
                        }
                    },
                    resolve(_source, args, context) {
                        return queryActorSpritesheetUrlResolver(args.urlType, context);
                    }
                },
                areaFileUrl: {
                    name: "areaFileUrl",
                    type: new GraphQLNonNull(GraphQLString),
                    args: {
                        areaId: {
                            type: new GraphQLNonNull(AreaIdType)
                        },
                        urlType: {
                            type: new GraphQLNonNull(FileUrlTypeType)
                        }
                    },
                    resolve(_source, args, context) {
                        return queryAreaFileUrlResolver(args.areaId, args.urlType, context);
                    }
                },
                characterList: {
                    name: "characterList",
                    type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(CharacterType))),
                    resolve(_source, _args, context) {
                        return queryCharacterListResolver(context);
                    }
                },
                defaultSpawnPoint: {
                    name: "defaultSpawnPoint",
                    type: new GraphQLNonNull(SpawnPointType),
                    resolve(_source, _args, context) {
                        return queryDefaultSpawnPointResolver(context);
                    }
                },
                isPatchOptimizerEnabled: {
                    name: "isPatchOptimizerEnabled",
                    type: new GraphQLNonNull(GraphQLBoolean),
                    resolve(_source, _args, context) {
                        return queryIsPatchOptimizerEnabledResolver(context);
                    }
                },
                itemDefinition: {
                    name: "itemDefinition",
                    type: new GraphQLNonNull(ItemDefinitionType),
                    args: {
                        ref: {
                            type: new GraphQLNonNull(ItemReferenceType)
                        }
                    },
                    resolve(_source, args, context) {
                        return queryItemDefinitionResolver(args.ref, context);
                    }
                },
                myCharacterId: {
                    name: "myCharacterId",
                    type: new GraphQLNonNull(CharacterIdType),
                    resolve(_source, _args, context) {
                        return queryMyCharacterIdResolver(context);
                    }
                },
                serverVersion: {
                    name: "serverVersion",
                    type: new GraphQLNonNull(GraphQLString),
                    resolve(_source, _args, context) {
                        return queryServerVersionResolver(context);
                    }
                },
                testError: {
                    name: "testError",
                    type: new GraphQLNonNull(GraphQLBoolean),
                    resolve(_source, _args, context) {
                        return queryTestErrorResolver(context);
                    }
                }
            };
        }
    });
    const MutationType: GraphQLObjectType = new GraphQLObjectType({
        name: "Mutation",
        fields() {
            return {
                setPatchOptimizerEnabled: {
                    name: "setPatchOptimizerEnabled",
                    type: new GraphQLNonNull(GraphQLBoolean),
                    args: {
                        newValue: {
                            type: new GraphQLNonNull(GraphQLBoolean)
                        }
                    },
                    resolve(_source, args, context) {
                        return mutationSetPatchOptimizerEnabledResolver(args.newValue, context);
                    }
                }
            };
        }
    });
    const ActorIdType: GraphQLScalarType = new GraphQLScalarType({
        name: "ActorId",
        ...config.scalars.ActorId
    });
    const GqlDateType: GraphQLScalarType = new GraphQLScalarType({
        name: "GqlDate",
        ...config.scalars.GqlDate
    });
    const LocalFileType: GraphQLScalarType = new GraphQLScalarType({
        name: "LocalFile",
        ...config.scalars.LocalFile
    });
    const PixelType: GraphQLScalarType = new GraphQLScalarType({
        description: "Unit of measurement in 2D screen space.",
        name: "Pixel",
        ...config.scalars.Pixel
    });
    const TimesPerSecondType: GraphQLScalarType = new GraphQLScalarType({
        name: "TimesPerSecond",
        ...config.scalars.TimesPerSecond
    });
    return new GraphQLSchema({
        query: QueryType,
        mutation: MutationType,
        types: [ActorIdType, ActorModelIdType, AreaIdType, CharacterIdType, GqlDateType, ItemDefinitionType, ItemReferenceType, LocalFileType, PixelType, TileType, TimesPerSecondType, UrlStringType, FileUrlTypeType, CharacterType, MutationType, QueryType, SpawnPointType, TileVectorLikeType]
    });
}
