/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */

import type { GqlScalar } from "grats";
import type { GqlDate as GqlDateInternal } from "./../shared/scalars";
import { GraphQLSchema, GraphQLObjectType, GraphQLString, GraphQLScalarType } from "graphql";
import { foo as queryFooResolver, whatever as queryWhateverResolver } from "./foo";
export type SchemaConfig = {
    scalars: {
        GqlDate: GqlScalar<GqlDateInternal>;
    };
};
export function getSchema(config: SchemaConfig): GraphQLSchema {
    const FooType: GraphQLObjectType = new GraphQLObjectType({
        name: "Foo",
        fields() {
            return {
                bar: {
                    name: "bar",
                    type: GraphQLString
                }
            };
        }
    });
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                foo: {
                    name: "foo",
                    type: FooType,
                    resolve() {
                        return queryFooResolver();
                    }
                },
                whatever: {
                    name: "whatever",
                    type: GraphQLString,
                    resolve() {
                        return queryWhateverResolver();
                    }
                }
            };
        }
    });
    const GqlDateType: GraphQLScalarType = new GraphQLScalarType({
        name: "GqlDate",
        ...config.scalars.GqlDate
    });
    return new GraphQLSchema({
        query: QueryType,
        types: [GqlDateType, FooType, QueryType]
    });
}
