{
 "title": "mp-game-server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "v_area_id", "label": "Area", "query": { "query": "label_values(areaId)" } }
  ]
 },
 "panels": [
  {
   "title": "Server Tick",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(server_tick_duration_bucket{areaId=\"$v_area_id\"}[$__rate_interval])))",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Game State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "active_npc_count{areaId=\"$v_area_id\"}",
     "legendFormat": "npcs"
    },
    {
     "expr": "active_character_count{areaId=\"$v_area_id\"}",
     "legendFormat": "characters"
    },
    {
     "expr": "server_area_count{areaId=\"$v_area_id\"}",
     "legendFormat": "areas"
    }
   ]
  },
  {
   "title": "Patch (Game Service -> Gateway)",
   "type": "timeseries",
   "description": "Game state patch sent per flush",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(server_to_gateway_sync_message_byte_size_sum{areaId=\"$v_area_id\"}[1m])",
     "legendFormat": "Throughput (per minute)"
    },
    {
     "expr": "rate(server_to_gateway_sync_message_byte_size_sum{areaId=\"$v_area_id\"}[1m]) / rate(server_to_gateway_sync_message_byte_size_count[1m])",
     "legendFormat": "Average patch size"
    }
   ]
  },
  {
   "title": "Patch (Gateway->Client)",
   "type": "timeseries",
   "description": "Game state patch sent per flush",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(gateway_to_game_client_sync_message_byte_size_sum{areaId=\"$v_area_id\"}[1m])",
     "legendFormat": "Throughput (per minute)"
    },
    {
     "expr": "rate(gateway_to_game_client_sync_message_byte_size_sum{areaId=\"$v_area_id\"}[1m]) / rate(gateway_to_game_client_sync_message_byte_size_count[1m])",
     "legendFormat": "Average patch size"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{job=\"server\", areaId=\"$v_area_id\"}[2m]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{job=\"server\", areaId=\"$v_area_id\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, max by(le) (increase(nodejs_gc_duration_seconds_bucket{kind=\"major\", areaId=\"$v_area_id\"}[$__rate_interval])))",
     "legendFormat": "Major"
    },
    {
     "expr": "histogram_quantile(0.95, max by(le) (increase(nodejs_gc_duration_seconds_bucket{kind=\"minor\", areaId=\"$v_area_id\"}[$__rate_interval])))",
     "legendFormat": "Minor"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=\"server\", areaId=\"$v_area_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{job=\"server\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"server\", areaId=\"$v_area_id\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{job=\"server\", areaId=\"$v_area_id\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=\"server\", areaId=\"$v_area_id\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=\"server\", areaId=\"$v_area_id\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{job=\"server\", areaId=\"$v_area_id\"}",
     "legendFormat": "Active Handler - {{instance}}"
    },
    {
     "expr": "nodejs_active_requests_total{job=\"server\", areaId=\"$v_area_id\"}",
     "legendFormat": "Active Request - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{job=\"server\", areaId=\"$v_area_id\"}",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{job=\"server\", areaId=\"$v_area_id\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{job=\"server\", areaId=\"$v_area_id\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  }
 ]
}