{
 "title": "mp-server (custom)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Server Tick",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(server_tick_interval_bucket[$__rate_interval])))",
     "legendFormat": "interval"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(server_tick_duration_bucket[$__rate_interval])))",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Game State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "active_npc_count", "legendFormat": "npcs" }
   ]
  },
  {
   "title": "Patch",
   "type": "timeseries",
   "description": "Game state patch sent per flush",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(game_state_flush_patch_size_bytes_sum[1m])",
     "legendFormat": "Throughput (per minute)"
    },
    {
     "expr": "rate(game_state_flush_patch_size_bytes_sum[1m]) / rate(game_state_flush_patch_size_bytes_count[1m])\n",
     "legendFormat": "Average patch size"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, max by(le) (increase(nodejs_gc_duration_seconds_bucket{kind=\"major\"}[$__rate_interval])))",
     "legendFormat": "Major"
    },
    {
     "expr": "histogram_quantile(0.95, max by(le) (increase(nodejs_gc_duration_seconds_bucket{kind=\"minor\"}[$__rate_interval])))",
     "legendFormat": "Minor"
    }
   ]
  },
  {
   "title": "User Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    { "expr": "active_user_count", "legendFormat": "users" },
    { "expr": "active_character_count", "legendFormat": "characters" },
    { "expr": "active_client_count", "legendFormat": "clients" }
   ]
  },
  {
   "title": "findPath",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(findPath_bucket[$__rate_interval])))",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "System logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{job=\"system_logs\"}"
    }
   ]
  },
  {
   "title": "Game server logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"docker-mp-server-1\"}"
    }
   ]
  }
 ]
}