apiVersion: 1

deleteDatasources:
  - name: "Mimir"
  - name: "Loki"

datasources:
  - name: "Mimir"
    type: "prometheus"
    access: "proxy"
    orgId: 1
    url: "http://mimir:9009/prometheus"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    uid: "mimir"

  - name: "Loki"
    type: "loki"
    access: "proxy"
    orgId: 1
    url: "http://loki:3100"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    uid: "loki"
