apiVersion: 1

deleteDatasources:
  - name: "Mimir"
  #- name: "Tempo"
  - name: "Loki"

datasources:
  - name: "Mimir"
    type: "prometheus"
    access: "proxy"
    orgId: 1
    url: "http://mimir:9009/prometheus"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    uid: "mimir"
    # jsonData:
    #   exemplarTraceIdDestinations:
    #     - datasourceUid: "tempo"
    #       name: "TraceID"

  # - name: "Tempo"
  #   type: "tempo"
  #   access: "proxy"
  #   orgId: 1
  #   url: "http://${TEMPO_HOST}:${TEMPO_PORT}"
  #   basicAuth: false
  #   isDefault: false
  #   version: 1
  #   editable: false
  #   apiVersion: 1
  #   uid: "tempo"
  #   jsonData:
  #     lokiSearch:
  #       datasourceUid: "loki"
  #     tracesToLogs:
  #       datasourceUid: "loki"
  #     nodeGraph:
  #       enabled: "true"
  #     serviceMap:
  #       datasourceUid: "mimir"
  - name: "Loki"
    type: "loki"
    access: "proxy"
    orgId: 1
    url: "http://loki:3100"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    uid: "loki"
    # jsonData:
    #   derivedFields:
    #     - datasourceUid: "tempo"
    #       matcherRegex: 'traceID=(\w+)'
    #       name: "TraceID"
    #       url: "$${__value.raw}"
