name: Test, Build, Deploy
on: [push]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  BUILD_VERSION: ${{ github.run_number }}

jobs:
  conventions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - run: pnpm lint
      - run: pnpm format

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - run: pnpm test

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/

      - name: Build application
        run: pnpm build
        env:
          NODE_ENV: production
          MP_SERVER_URL: wss://k573.dev
          MP_AUTH_PUBLISHABLE_KEY: ${{ secrets.AUTH_PUBLISHABLE_KEY }}
          MP_BUILD_VERSION: ${{ env.BUILD_VERSION }}

      - name: Log in with Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker compose build
          docker compose push

  deploy:
    needs: [conventions, test, build]
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load docker-compose file into environment
        run: echo "DOCKER_COMPOSE_BASE64=$(cat docker-compose.yaml | base64 -w 0)" >> $GITHUB_ENV

      - name: Deploy via SSH action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.DEPLOY_SSH_HOST }}
          username: ${{ vars.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          envs: DOCKER_REGISTRY,DOCKER_USERNAME,DOCKER_PASSWORD,DOCKER_COMPOSE_BASE64
          script_stop: true
          script: |
            cd ~
            echo $DOCKER_COMPOSE_BASE64 > base64.txt
            cat base64.txt | base64 --decode > docker-compose.yaml
            rm base64.txt
            echo $DOCKER_PASSWORD | docker login $(echo $DOCKER_REGISTRY) -u $(echo $DOCKER_USERNAME) --password-stdin
            echo "MP_AUTH_SECRET_KEY=\"${{ secrets.AUTH_SECRET_KEY }}\"" > .env
            echo "MP_BUILD_VERSION=\"${{ env.BUILD_VERSION }}\"" >> .env
            docker compose pull
            docker compose --env-file .env up -d --remove-orphans
            docker compose run db-migrations
            docker system prune -f
            docker image prune -af
