name: Test, Build, Deploy
on: [push]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REGISTRY_URL: ghcr.io/${{ github.actor }}
  DOCKER_COMPOSE_ENV: prod
  DOCKER_IMAGE_VERSION: latest
  BUILD_VERSION: ${{ github.run_number }}

jobs:
  conventions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install_node_things/
      - run: pnpm lint
      - run: pnpm format

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install_node_things/
      - run: pnpm test

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Log in with Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          cd docker
          docker compose build
          docker compose push

  deploy:
    needs: [conventions, test, build]
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload docker compose runtime dependencies
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avz --delete
          path: docker/
          remote_path: ~/docker
          remote_host: ${{ vars.DEPLOY_SSH_HOST }}
          remote_user: ${{ vars.DEPLOY_SSH_USERNAME }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy via SSH action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.DEPLOY_SSH_HOST }}
          username: ${{ vars.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          envs: DOCKER_REGISTRY_URL,DOCKER_COMPOSE_ENV,DOCKER_IMAGE_VERSION
          script_stop: true
          script: |
            cd ~/docker
            echo "MP_AUTH_SECRET_KEY=\"${{ secrets.AUTH_SECRET_KEY }}\"" > .env.local
            echo "MP_AUTH_PUBLISHABLE_KEY=\"${{ secrets.AUTH_PUBLISHABLE_KEY }}\"" >> .env.local
            echo "MP_BUILD_VERSION=\"${{ env.BUILD_VERSION }}\"" >> .env.local
            docker compose pull
            docker compose up -d --remove-orphans --no-build
            docker compose run migrations
            docker system prune -f
            docker image prune -af
